#! /bin/sh
#
str1="Сегодня"
str2="Рассвет: 9:19 AM, закат 5:06 PM"
str3="Днем: Cloudy"
str4="Температура: 0°C - -2°C"
str5="Влажность: 100%"
str6="Давление: 1017.9mb"
str7="Ветер: W, скорость 6kph"
str8="Ночью: Cloudy"
str9="Температура: 0°C - -2°C"
str10="Влажность: 100%"
str11="Ветер: W, скорость 6kph"
str12="Thursday"
str13="Рассвет:9:19 AM, закат 5:06 PM"
str14="Днем: Light Snow Showers"
str15="Температура: -2°C - -4°C"
str16="Влажность: 89%"
str17="Ветер: NNW, скорость 11kph"
str18="Ночью: Light Snow Showers"
str19="Температура: -2°C - -4°C"
str20="Влажность: 89%"
str21="Ветер: NNW, скорость 11kph"
str22="Friday"
str23="Рассвет: 9:17 AM, закат5:08 PM"
str24="Днем: Light Snow Showers"
str25="Температура: -3°C - -8°C"
str26="Влажность: 88%"
str27="Ветер: NNE, скорость 14kph"
str28="Ночью: Snow Showers"
str29="Температура: -3°C - -8°C"
str30="Влажность: 94%"
str31="Ветер: NE, скорость 10kph"
str32="Thu Jan 29 07:01:05 MSK 2009"
echo "<openbox_pipe_menu>" 
echo "<menu id=\"today\" label="\"$str1\"">"
echo "<item label="\"$str2\""/>"
echo "<separator label="\"$str3\""/>"
echo "<item label="\"$str4\""/>"
echo "<item label="\"$str5\""/>"
echo "<item label="\"$str6\""/>"
echo "<item label="\"$str7\""/>"
echo "<separator label="\"$str8\""/>"
echo "<item label="\"$str9\""/>"
echo "<item label="\"$str10\""/>"
echo "<item label="\"$str11\""/>"
echo "</menu>"
echo "<menu id=\"tommor\" label="\"$str12\"">"
echo "<item label="\"$str13\""/>"
echo "<separator label="\"$str14\""/>"
echo "<item label="\"$str15\""/>"
echo "<item label="\"$str16\""/>"
echo "<item label="\"$str17\""/>"
echo "<separator label="\"$str18\""/>"
echo "<item label="\"$str19\""/>"
echo "<item label="\"$str20\""/>"
echo "<item label="\"$str21\""/>"
echo "</menu>"
echo "<menu id=\"datommor\" label="\"$str22\"">"
echo "<item label="\"$str23\""/>"
echo "<separator label="\"$str24\""/>"
echo "<item label="\"$str25\""/>"
echo "<item label="\"$str26\""/>"
echo "<item label="\"$str27\""/>"
echo "<separator label="\"$str28\""/>"
echo "<item label="\"$str29\""/>"
echo "<item label="\"$str30\""/>"
echo "<item label="\"$str31\""/>"
echo "</menu>"
echo "</openbox_pipe_menu>"
